### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by timnugent** [Uniswap/smart-order-router#11]
I'm running this code with a local JSON-RPC node but finding it to be pretty slow (8 core 4ghz, 32 GB RAM, all SSDs etc) . It averages around 7 seconds to generate a route, vs ~2-3 seconds for the public endpoint that serves the Uniswap UI. Are there any optimizations that might be used to speed  things up? Caching, or excluding certain pools perhaps?

**Comment by willpote** [comment]
Are you running it with the CLI? Each time you request a quote using the CLI the code will make a query to the Subgraph to fetch all the candidate pools for routing. This can take 5+ seconds so is probably the delay you are seeing.

In the hosted API we cache this data which is why it is quicker.

We are actually working on a solution for this currently- we plan to publish the pools to IPFS, then we'll update this package to fetch the pools from there instead of the Subgraph. Should speed things up significantly.

**Comment by timnugent** [comment]
Yes, running the CLI version.

Ok - that's good to know re: IPFS. Look forward to the updates.

**Comment by quan-unizen** [comment]
How is it going @willpote ? Its taking me 16s to fetch the route

**Comment by kasparkallas** [comment]
Hi! Any update on this? Also find it to be a tad slow.
