### ISSUE TITLE
Could not find route

### ISSUE THREAD

**Issue by timnugent** [Uniswap/smart-order-router#9]
Trying to find a route between e.g. NMR and BAL, this fails:

NMR : 0x1776e1F26f98b1A5dF9cD347953a26dd3Cb46671
BAL : 0xba100000625a3754423978a60c9317c58a424e3D

./bin/cli quote --tokenIn 0x1776e1F26f98b1A5dF9cD347953a26dd3Cb46671 --tokenOut 0xba100000625a3754423978a60c9317c58a424e3D --amount 1000 --exactIn --recipient 0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B
Could not find route. Run in debug mode for more info.

But it seems to work ok at https://app.uniswap.org/#/swap

Other pairs do work as expected.

I ran with the debugger (--inspect) but this doesn't give me any more info. I'm using Alchemy as the JSON-RPC host

**Comment by willpote** [comment]
Currently this package only supports routing on V3. Since [NMR is not liquid on V3](https://info.uniswap.org/#/tokens/0x1776e1f26f98b1a5df9cd347953a26dd3cb46671) this package can't find a route.

https://app.uniswap.org/#/swap has logic for finding routes on V2, so it is showing you a V2 swap. 

We're working on adding V2 support to this package so soon youll be able to find a route for these tokens

**Comment by timnugent** [comment]
Ah that makes sense. Look forward to seeing V2 support here too.
